---
- name: install | installing python modules
  pip:
    name: "{{ item }}"
    state: present
  with_items:
    - virtualenv
    - virtualenvwrapper
    
- name: install | installing django
  pip:
    name: "django"
    state: present
  when: >
        (django_version is defined and django_version == "latest") or
        django_version is not defined

- name: install | installing django
  pip:
    name: "django=={{ django_version }}"
    state: present
  when: django_version is defined and django_version != "latest"
